name: Cron Job

on:
  schedule:
    - cron: '*/30 * * * *'  

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' 

      - name: Install dependencies
        run: npm install

      - name: Run notification script
        run: node netlify/functions/firebase.js
